version: "3.0"

services:
  shiny:
    image: rocker/shiny:latest
    restart: always
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
      - '3838:3838'
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - "./shiny-server/app:/srv/shiny-server/"
      
  shiny-auth0:
    container_name: shiny-auth0
    image: lgraveland/shiny-auth0:latest
    volumes:
     - "./shiny-auth0/.env:/opt/code/.env"
    ports:
      - '3000:3000'
  
  shiny-nginx:
    container_name: shiny-nginx
    image: nginx:latest
    volumes:
      - "./nginx/:/etc/nginx/"
    ports : 
      - '800:80'
      - '443:443'

volumes:
  shiny_logs:
