version: "3.0"

services:
  shiny:
    #container_name: shiny
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    image: rocker/shiny:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
      - '3838:3838'
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - "./shiny-server/app:/srv/shiny-server/"
      # Comment the line below out for initial testing. With it commented out,
      # going to localhost:80 in one's web browser will show a "Welcome to
      # Shiny Server!" diagnostics page.
      # - './mountpoints/apps:/srv/shiny-server'
  
  shiny-auth0:
    container_name: shiny-auth0
    image: lgraveland/shiny-auth0:latest
    volumes:
     - "./shiny-auth0/.env:/opt/code/.env"
    #restart: always
    ports:
      - '3000:3000'
  
  shiny-nginx:
    container_name: shiny-nginx
    image: nginx:latest
    volumes:
      - "./nginx/:/etc/nginx/"
    #build:
    #  dockerfile: Dockerfile-shiny-nginx
    #  context: .
    #restart: always
    ports : 
      - '800:80'
      - '443:443'

volumes:
  shiny_logs:
